// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - generated by `opennextjs-cloudflare build` after `next build`
import openNextHandler from "../.open-next/worker.js";

export { Room } from "./room";

const ROOM_PATH = /^\/ws\/([A-Za-z0-9]+)\/?$/;

export default {
  async fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);
    const match = url.pathname.match(ROOM_PATH);
    if (match) {
      const code = match[1].toUpperCase();
      const upgrade = request.headers.get("upgrade");
      if (upgrade !== "websocket") {
        return new Response("expected websocket", { status: 400 });
      }
      const id = env.ROOM.idFromName(code);
      const stub = env.ROOM.get(id);
      const proxied = new Request(url.toString(), request);
      proxied.headers.set("x-room-code", code);
      return stub.fetch(proxied);
    }

    return openNextHandler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;
